---
- name: EC2 Playbook
  hosts: all
  become: yes
  
  tasks:
  - name: Disable Docker Service
    service:
      name: docker
      state: stopped
      enabled: no

  - name: Install Apache HTTPD
    yum:
      name: httpd
      state: present

  - name: Start Apache HTTPD Service
    se

