---
- hosts: ec2
  become: true
  tasks:
  - name: Disable Docker
    service:
      name: docker
      enabled: false
      state: stopped
  - name: Install Apache
    yum:
      name: httpd
      state: latest
      update_cache: yes
  - name: Start Apache HTTPD Service
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Copy files
    copy:
      src: /hello-2048/public_html/
      dest: /var/www/html/
      owner: apache
      group: apache
      mode: "0644"
      directory_mode: "0755"

